### ISSUE TITLE
invalid .ccc file in Nuke OCIO CDL Transform node triggers infinite loop

### ISSUE THREAD

**Issue by KevinJW** [AcademySoftwareFoundation/OpenColorIO#410]
Load this file into Nuke node and loop for ever...

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/foundry/nuke-9.0v8/plugins/ocionuke/cdl.py", line 278, in set_first_cccid
    allcc = _xml_to_cdltransforms(xml)
  File "/opt/foundry/nuke-9.0v8/plugins/ocionuke/cdl.py", line 55, in _xml_to_cdltransforms
    tree = ET.fromstring(xml)
  File "/opt/foundry/nuke-9.0v8/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/opt/foundry/nuke-9.0v8/lib/python2.7/xml/etree/ElementTree.py", line 1641, in feed
    self._parser.Parse(data, 0)
  File "/opt/foundry/nuke-9.0v8/lib/python2.7/xml/etree/ElementTree.py", line 1544, in _start_list
    return self.target.start(tag, attrib)
  File "/opt/foundry/nuke-9.0v8/lib/python2.7/xml/etree/ElementTree.py", line 1420, in start
    self._last = elem = self._factory(tag, attrs)
RuntimeError: maximum recursion depth exceeded

[missing_id.ccc.txt](https://github.com/imageworks/OpenColorIO/files/474399/missing_id.ccc.txt)

xmllint shows the file is not valid
element ColorCorrection: Schemas validity error : Element '{urn:ASC:CDL:v1.01}ColorCorrection': The attribute 'id' is required but missing.
missing_id.ccc fails to validate

But it would be nice to handle this slightly more gracefully than locking up Nuke.

Kevin

**Comment by KevinJW** [comment]
I tested this in a Nuke 14.1 and it appears to now be fixed.
